
import { FunctionDeclaration, Schema, Type } from "@google/genai";

// Helper to create simple tool definitions
const defTool = (name: string, description: string, params: {[key: string]: Schema} = {}, required: string[] = []): FunctionDeclaration => {
  return {
    name,
    description,
    parameters: {
      type: Type.OBJECT,
      properties: params,
      required,
    },
  };
};

export const allTools: FunctionDeclaration[] = [
  // --- CORE OPS (12) ---
  defTool("set_document_type", "Set document mode (GENERAL, ID_CARD, FINANCIAL)", { type: { type: Type.STRING, enum: ["GENERAL", "ID_CARD", "FINANCIAL"] } }, ["type"]),
  defTool("toggle_intel_mode", "Toggle Agent Delta (Intel)", { enabled: { type: Type.BOOLEAN } }, ["enabled"]),
  defTool("trigger_undo", "Undo last action"),
  defTool("trigger_redo", "Redo last action"),
  defTool("reset_workspace", "Reset application state"),
  defTool("set_operation_prompt", "Set the main operation prompt text", { text: { type: Type.STRING } }, ["text"]),
  defTool("execute_operation", "Execute the document edit/generation"),
  defTool("open_asset_fab", "Open Agent Gamma Asset Fabrication", { prompt: { type: Type.STRING } }),
  defTool("run_audit", "Trigger Agent Omega Forensic Audit"),
  defTool("print_hardcopy", "Trigger browser print dialog"),
  defTool("export_to_pdf", "Export current workspace to PDF"),
  defTool("export_to_png", "Export current workspace to PNG"),

  // --- ISP (Image Signal Processing) (20) ---
  defTool("isp_set_brightness", "Set image brightness (0-200)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_contrast", "Set image contrast (0-200)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_saturation", "Set image saturation (0-200)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_grayscale", "Set grayscale percentage (0-100)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_sepia", "Set sepia percentage (0-100)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_invert", "Set invert percentage (0-100)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_blur", "Set blur radius px (0-20)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_hue_rotate", "Set hue rotation degrees (0-360)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_set_opacity", "Set opacity percentage (0-100)", { value: { type: Type.NUMBER } }, ["value"]),
  defTool("isp_reset_all", "Reset all ISP filters to default"),
  defTool("isp_apply_preset_cctv", "Apply CCTV security camera look"),
  defTool("isp_apply_preset_night_vision", "Apply Night Vision (Green) look"),
  defTool("isp_apply_preset_thermal", "Apply Thermal imaging look"),
  defTool("isp_apply_preset_xray", "Apply X-Ray inverted look"),
  defTool("isp_apply_preset_photocopy", "Apply high contrast photocopy look"),
  defTool("isp_apply_preset_blueprint", "Apply technical blueprint look"),
  defTool("isp_apply_preset_crt", "Apply CRT monitor look with scanlines"),
  defTool("isp_apply_preset_noir", "Apply cinematic Noir look"),
  defTool("isp_apply_preset_polaroid", "Apply vintage Polaroid color grading"),
  defTool("isp_apply_preset_vhs", "Apply damaged VHS tape look"),

  // --- SPATIAL TRANSFORMS (8) ---
  defTool("spatial_rotate", "Rotate image by degrees", { degrees: { type: Type.NUMBER } }, ["degrees"]),
  defTool("spatial_zoom", "Set zoom level (0.1 to 5.0)", { scale: { type: Type.NUMBER } }, ["scale"]),
  defTool("spatial_flip_h", "Flip image horizontally"),
  defTool("spatial_flip_v", "Flip image vertically"),
  defTool("spatial_reset_transforms", "Reset all spatial transforms"),
  defTool("spatial_center_view", "Center the image in the viewport"),
  defTool("spatial_fit_screen", "Fit image to screen bounds"),
  defTool("spatial_fill_screen", "Fill screen with image (crop)"),

  // --- UI/SYSTEM CONTROL (12) ---
  defTool("sys_toggle_crt", "Toggle CRT monitor effect"),
  defTool("sys_toggle_grid", "Toggle alignment grid overlay"),
  defTool("sys_toggle_scanlines", "Toggle scanline overlay"),
  defTool("sys_toggle_hud", "Toggle Heads Up Display elements"),
  defTool("sys_toggle_debug", "Toggle Debug Mode overlay"),
  defTool("sys_toggle_audio", "Toggle UI sound effects"),
  defTool("sys_clear_terminal", "Clear the terminal history"),
  defTool("sys_show_status", "Show system status report"),
  defTool("sys_reboot", "Simulate system reboot sequence"),
  defTool("sys_lock_terminal", "Lock terminal input"),
  defTool("ui_close_terminal", "Close/Hide the root terminal window"),
  defTool("sys_matrix_mode", "Toggle Matrix rain visual effect"),

  // --- REAL-TIME OSINT (Open Source Intelligence) (20) ---
  defTool("osint_google_search", "Perform a real-time Google Search", { query: { type: Type.STRING } }, ["query"]),
  defTool("osint_image_search", "Search for images matching description", { description: { type: Type.STRING } }, ["description"]),
  defTool("osint_find_pdf", "Search for PDF documents on a topic", { topic: { type: Type.STRING } }, ["topic"]),
  defTool("osint_lookup_ip", "Lookup IP address geolocation/info", { ip: { type: Type.STRING } }, ["ip"]),
  defTool("osint_lookup_domain", "Lookup Domain WHOIS info", { domain: { type: Type.STRING } }, ["domain"]),
  defTool("osint_lookup_username", "Search for username across social platforms", { username: { type: Type.STRING } }, ["username"]),
  defTool("osint_lookup_mac", "Lookup MAC address OUI vendor", { mac: { type: Type.STRING } }, ["mac"]),
  defTool("osint_search_breaches", "Check if email is in known breaches", { email: { type: Type.STRING } }, ["email"]),
  defTool("osint_analyze_exif", "Analyze EXIF data of current asset"),
  defTool("osint_reverse_image", "Perform reverse image search on current asset"),
  defTool("osint_scan_ports", "Scan common ports of target IP", { ip: { type: Type.STRING } }, ["ip"]),
  defTool("osint_check_ssl", "Check SSL certificate of domain", { domain: { type: Type.STRING } }, ["domain"]),
  defTool("osint_get_http_headers", "Fetch HTTP headers from URL", { url: { type: Type.STRING } }, ["url"]),
  defTool("osint_find_subdomains", "Find subdomains of a target", { domain: { type: Type.STRING } }, ["domain"]),
  defTool("osint_social_graph", "Generate social graph for target", { target: { type: Type.STRING } }, ["target"]),
  defTool("osint_darkweb_search", "Search Onion/Darkweb indexes", { query: { type: Type.STRING } }, ["query"]),
  defTool("osint_news_search", "Search current news wire", { topic: { type: Type.STRING } }, ["topic"]),
  defTool("osint_gov_records", "Search public government records", { name: { type: Type.STRING } }, ["name"]),
  defTool("osint_patent_search", "Search patent databases", { keywords: { type: Type.STRING } }, ["keywords"]),
  defTool("osint_verify_fact", "Verify a fact using multiple sources", { statement: { type: Type.STRING } }, ["statement"]),

  // --- CRYPTOGRAPHY & CODING (20) ---
  defTool("crypto_hash_md5", "Generate MD5 hash of text", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_hash_sha1", "Generate SHA1 hash of text", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_hash_sha256", "Generate SHA256 hash of text", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_base64_encode", "Encode text to Base64", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_base64_decode", "Decode Base64 to text", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_rot13", "Apply ROT13 cipher", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_hex_encode", "Convert text to Hex", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_hex_decode", "Convert Hex to text", { hex: { type: Type.STRING } }, ["hex"]),
  defTool("crypto_url_encode", "URL Encode string", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_url_decode", "URL Decode string", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_binary_encode", "Convert text to Binary", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_binary_decode", "Convert Binary to text", { binary: { type: Type.STRING } }, ["binary"]),
  defTool("crypto_caesar_cipher", "Apply Caesar Cipher", { text: { type: Type.STRING }, shift: { type: Type.NUMBER } }, ["text", "shift"]),
  defTool("crypto_generate_uuid", "Generate a random UUID"),
  defTool("crypto_generate_password", "Generate strong random password", { length: { type: Type.NUMBER } }),
  defTool("crypto_detect_hash_type", "Identify hash type", { hash: { type: Type.STRING } }, ["hash"]),
  defTool("crypto_check_strength", "Check password strength", { password: { type: Type.STRING } }, ["password"]),
  defTool("crypto_morse_encode", "Encode text to Morse Code", { text: { type: Type.STRING } }, ["text"]),
  defTool("crypto_morse_decode", "Decode Morse Code", { morse: { type: Type.STRING } }, ["morse"]),
  defTool("crypto_qrcode_gen", "Generate QR Code for data", { data: { type: Type.STRING } }, ["data"]),

  // --- STEGANOGRAPHY & FORENSICS (15) ---
  defTool("stego_embed_text", "Embed text into image (LSB)", { text: { type: Type.STRING } }, ["text"]),
  defTool("stego_extract_text", "Extract hidden text from image (LSB)"),
  defTool("forensics_strings", "Extract printable strings from binary"),
  defTool("forensics_hexdump", "View Hex dump of asset"),
  defTool("forensics_entropy_calc", "Calculate Shannon entropy of asset"),
  defTool("forensics_detect_faces", "Run facial recognition algorithms"),
  defTool("forensics_detect_objects", "Run object detection algorithms"),
  defTool("forensics_detect_text", "Run OCR text detection"),
  defTool("forensics_ela_analysis", "Perform Error Level Analysis"),
  defTool("forensics_noise_analysis", "Analyze sensor noise patterns"),
  defTool("forensics_clone_detection", "Detect cloned/healing tool usage"),
  defTool("forensics_metadata_viewer", "View full metadata"),
  defTool("forensics_gps_extract", "Extract GPS coordinates if available"),
  defTool("forensics_color_histogram", "Analyze color distribution"),
  defTool("forensics_match_database", "Match asset against known databases"),

  // --- UTILITY & MATH (10) ---
  defTool("util_convert_units", "Convert units", { value: { type: Type.NUMBER }, from: { type: Type.STRING }, to: { type: Type.STRING } }, ["value", "from", "to"]),
  defTool("util_calculate", "Evaluate math expression", { expression: { type: Type.STRING } }, ["expression"]),
  defTool("util_get_timestamp", "Get current UNIX timestamp"),
  defTool("util_regex_match", "Test Regex pattern", { pattern: { type: Type.STRING }, text: { type: Type.STRING } }, ["pattern", "text"]),
  defTool("util_json_format", "Format/Prettify JSON", { json: { type: Type.STRING } }, ["json"]),
  defTool("util_lorem_ipsum", "Generate placeholder text", { words: { type: Type.NUMBER } }),
  defTool("util_generate_iban", "Generate valid test IBAN"),
  defTool("util_generate_credit_card", "Generate valid test Credit Card number"),
  defTool("util_generate_ssn", "Generate valid test SSN"),
  defTool("util_whoami", "Display current user session info")
];
